apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: default
spec:
  minVersion: VersionTLS12
  cipherSuites:
    ## 只允許高安全性的加密演算法套件
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

---
## 入口為 websecure 的 IngressRoute，預設會加入 default-secure-headers Middleware，無須自行加入。
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: default-secure-headers
  namespace: default
spec:
  headers:
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    forceSTSHeader: true
