## 入口為 websecure 的 IngressRoute，預設會加入 default-secure-headers Middleware，無須自行加入。
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-secure-headers
  namespace: kube-system
spec:
  headers:
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    forceSTSHeader: true
