apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: backup-server
  namespace: vstarchain
spec:
  repo: https://github.com/yhleu/rancher-fleet.git
  branch: main
  paths:
    - apps/traefik
  targets:
  - clusterSelector:
    matchLabels:
      type: backup-server
