## Traefik
defaultNamespace: kube-system
helm:
  repo: https://traefik.github.io/charts
  chart: traefik
  version: 27.0.2
  releaseName: traefik
  valuesFiles:
    - traefik-values.yaml
kustomize:
  dir: ./kustomize
targetCustomizations:
- name: backup-server
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: backup-server
  helm:
    valuesFiles:
      - overlays/backup-server/traefik-values.yaml
  kustomize:
    dir: overlays/backup-server

overrideTargets:
  - clusterSelector:
      matchLabels:
        type: backup-server