apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: default
spec:
  redirectRegex :
    permanent: true
    regex: "^https://backup.rd0.hwacom.com"
    replacement: "https://backup.rd0.hwacom.com/portal"
