apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portal
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    ## Portal route
    - match: Host(`${SVC_DOMAIN_NAME}`) && Path(`/`)
      kind: Rule
      services:
        - name: portal
          port: 80
      middlewares:
        - name: redirect
    - match: Host(`${SVC_DOMAIN_NAME}`) && PathPrefix(`/portal/`)
      kind: Rule
      services:
        - name: portal
          port: 80
  tls:
    secretName: portal-tls-secret