kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: vstarchain-root
  namespace: fleet-local
spec:
  repo: https://github.com/yhleu/rancher-fleet.git
  branch: main
  paths:
    - workspace/
    - repos/testing
    - repos/production
  targets:
    - clusterSelector: {}