## Traefik helm value overlay for backup-server
ports:
  # websecure:
    # exposedPort: 8443
  # 安裝 MinIO時，應啟用minio-api entrypoint
  minio-api:
    port: 9000
    expose:
      default: true
    exposedPort: 9000
    protocol: TCP
    tls:
      enabled: true
    # middlewares:
      # - default-default-secure-headers@kubernetescrd
