auth:
  ## The secret has to contain the keys `root-user` and `root-password`)
  existingSecret: minio-secret
  
podSecurityContext:
  fsGroup: 10321

containerSecurityContext:
  runAsUser: 10321
  runAsGroup: 10321

podAnnotations:
  velero.io/exclude-from-backup: "true"
  
resourcesPreset: "none"

persistence:
  ## PVC Storage Request for MinIO&reg; data volume
  size: 8Gi

extraEnvVars:
  - name: TZ
    value: Asia/Taipei
